[quote.epigraph, , Isaiah 42:16]
____
I will bring the blind by a way that they knew not.
____

== Introduction

The following pages contain the substance of a letter from the author to a relation:
some of her family and several Friends who have seen them,
apprehend that they contain much instruction to the Christian traveller,
who has "`put his hand to the plough.`"
They hold forth encouragement to bow under the earliest
impressions of the power of the Most High,
to be attentive to the Shepherd`'s voice,
and to allow all within them to be humbled in submission to his requirings.
They show how important it is for those who, like the writer of this narrative,
have purchased an inheritance in righteousness,
to take heed that they do not let go their hold,
but attend to the injunction of the wise man, "`buy the truth, and sell it not.`"
And they are a call on those who have a birthright in our religious Society,
to prize their privilege; seeing the instance before us is a proof, among many,
of the difficulties and trials through which those have to pass,
who are called out of the world, to be faithful labourers in the heavenly vineyard.

From the following lively specimen,
it is to be regretted that no further documents are to be
found of the religious progress of this our dear friend,
who lived and died respected and beloved.^
footnote:[This account was originally edited by Frederick Smith:
two editions of it were published in the year 1797.]
