== Life of Margaret Lucas

I was born in the year 1701, in Fleet-street, London; my father,
whose name was James Brindley, kept a china-shop at the corner of Fetter-lane.
I was the youngest of fourteen children:
my mother died when I was one year and a half old;
after which my father removed to Vauxhall, where he erected a pottery,
for making Dutch or stone ware, and married a second wife, who, dying before him,
left two children.
When I was about seven years old, my father died, leaving six orphans,
two of them younger than myself, with no other relation that we knew of, except my aunt,
who was my father`'s sister, and married the person hereafter mentioned as my uncle.
My father dying without a will, left things in disorder; and Elias Turner,
who was one of the three directors of the South Sea Company, being the greatest creditor,
sent for my uncle from Leek to London, and advised him to act as guardian for us.
Three of us, at my father`'s death, were under the care of his housekeeper,
the wife of one of his clerks.
She was very careful over us, and brought us up strictly in the protestant religion.
My eldest sister, being weakly, lived much with my aunt in the country,
except in the time of her education;
and my little brother and sister were taken down to Leek by my aunt,
on her return from visiting us, after my father`'s death;
but the little boy did not live long.
My uncle had a mind, at this time, to bring me down also, saying that,
upon seeing my innocent amusements, he had a particular respect for me;
but Elias Turner would not consent to it, and I, with my brother and sister,
continued under the care of the housekeeper some years longer.
My uncle at times repeating his desire to have us with him,
and it being left to my choice, in the year 1718 I came down.

I had conceived the country to be a more delightful place than I at first found it;
and I expressed to the maid, that accompanied me, my dissatisfaction and disappointment.
She stayed with me till the return of the coach, and left me a little sad;
yet my uncle and aunt were full of love towards me,
and I was careful of my expressions on the difference of situation.
But what added to my grief at this juncture was the behaviour of my eldest sister,
whom I did not remember to have seen before my coming down:
she gave my uncle so much uneasiness, that he sent her out of the town; and,
though he strove to prevent it, she married his apprentice,
and never was re-admitted to his house while I lived there.
On occasion of this, and the irksomeness of my situation,
my uncle thought proper to board me at school,
though not altogether on account of my learning,
for I was then thought dexterous beyond most of my years; and indeed, from a child,
there was a flexibility in my temper, which, like the softened wax,
seemed fit for impression and improvement.
My uncle concluded that I might meet with something there to improve and divert my mind,
though I concealed my sorrow to the best of my power.
He took me to governess Hyde`'s, in order to board me there:
but there lived in Smythy Door, Manchester,
a widow whose husband died some pounds in my father`'s debt;
and my uncle calling for the money, and telling her whose daughter I was, she said,
if he pleased, she would board me, and I might go to a day school.
My uncle inquired into her character, and consulted with one Nichols, a yarn merchant,
in the Deansgate, who advised him to accept the offer; telling me that his house,
if I did not like the other, should be my home;
and here I always met with a kind reception.

My uncle stayed with me a few days, and then left me with the widow and her daughter,
the only child she had.
I liked my new situation very well; it was much more agreeable to me than Leek.
The widow and her daughter were Presbyterians; but my uncle ordered me my liberty,
and that I should go to church; which she never forbade,
though she was very strict in her own way of worship, and kept good order in the house,
with family prayer night and morning.
From these I never absented myself,
and I still remember the pleasure I then received from the books I read,
the repetition of my catechism, and those forms of prayers adapted to my years;
always esteeming those I believed to be religious.

I stayed at Manchester till the latter end of the year,
and spent the winter agreeably both to my uncle and myself.
In the spring he took a journey to London,
and as my younger sister had been brought from there while young,
he thought fit to take her with him for her improvement; and there she stayed four years.
Though I was left at my uncle`'s as by myself,
I did not regret the loss of these two sisters, who were indeed but as strangers to me,
and amends were fully made by my uncle bringing down my other sister,
with whom I had lived under the care of our housekeeper.
This gave me, as it were, new life, for the month that she stayed with us;
but her departure went very hard with me; and my uncle,
who ever sought before I went to meetings, to make me happy, according to his notion,
proposed to take me to Manchester again.
This pleased me, and the widow received me kindly.
She never asked me to go to chapel, yet I many times went at pleasure,
and have since found occasion to remember what I met with there.
I stayed with her till the town was in confusion about tory and whig;
and as she was afraid of the consequence, she desired my uncle to take me home.

I was now past thirteen, and quite reconciled to my station,
growing in my uncle and aunt`'s favour, and in love towards them.
They punctually fulfilled their promise,
that I should lack nothing that was fit for me to have;
and though I had learned to dance in London, a dancing-master coming to the town,
my uncle sent me to him, it being a diversion which, as I was very agile,
it was said I was fit for; and indeed I was very fond of it.

When I was past fourteen, my brother came down to see me;
and my uncle still studying my improvement, sent me to learn writing, to make pastry,
and, on the return of the dancing master, to his school again.
This gave me an extensive acquaintance; and as I had acquired,
from the teachings of my London master, a different air, as it is termed,
I generally went off with applause; which was not less pleasing to my uncle and aunt,
than to myself.
He often showed his fondness for me at my return home--taking me
to his knee--asking if there was anything lacking in my dress,
which my acquaintance had, and I had a mind to have--saying he would buy it for me;
but his love prevented my much asking,
for no sooner did he see a new mode than he mentioned it;
nor do I remember that I ever asked him for anything which he denied me.

I was now past fifteen, and there coming two singing masters,
who taught to sing psalms by notes, my uncle sent me to them.
I went with many more, having great delight therein, as also in the worship of God,
as I had been taught.

Here I cannot but observe, how many different inventions there are,
to divert the minds of youth from opportunities of seeking after the one thing needful;
yet it was in the midst of these hurries that I began
to make reflections concerning the clergy,
and to account them worthy of double honour; esteeming them most happy,
as their employment consisted of devotion to God.
I therefore concluded they had a peculiar advantage in the mysteries of divine things,
and a more thorough knowledge of the Lord than others; often saying,
if I had been a boy I would have been brought up at the University,
as my brother was designed by my father to have been.

About this time some persons sought my company, by way of courtship;
but I gave them no encouragement, for I kept myself much reserved on that account;
going on in an earnest pursuit of my duties, as I had been taught,
which proved a comfort to my uncle and aunt.

When about sixteen, my uncle made me an assistant in the family, and on the First-days,
I not only read and gave out the psalms, but also the family prayers,
when my uncle was from home, or any way indisposed;
so that now I stood high in their favour,
with respect both to their religious and temporal enjoyments.
Indeed, I have many times since, thought my distressed uncle was similar to Micah, who,
we read, thought himself blessed when he had consecrated the Levite for his priest; but,
alas! how soon did the priest not only leave Micah, but take away his image: so,
though I stole not my uncle`'s god, yet I broke his peace,
and left him to contemplate the uncertainty of the
delight which is fixed on transient objects.

My uncle now intending my advancement, as he said, left his own small,
though convenient house, to take a larger,
for the better accommodation of me and my many acquaintances;
little suspecting that the removal would overthrow his happiness; but so it was.
This house stood opposite the gates of the church, so called,
where I was frequently reminded of the mortality of the body,
and was thereby struck with many serious reflections on the state of eternity,
and the immortality of the soul.

As I lived so near, I often waited upon the corpse to the grave,
musing in myself how it must be with the deceased in the hour of death; for,
though I had often heard that sentence pronounced, by the priest, in which it is said,
"`We commit the body to the ground,
(note) in sure and certain hope of the resurrection to eternal life;`" yet,
upon the strictest review,
I could not find I had any evidence of that hope abiding in me.
And though my reasonings would have led me to conclude it was an
immediate gift of God to the soul at the time of departure,
and my esteem for the clergy induced the belief, that it was an assurance given to them,
and that the people must build their hope thereon;
yet my uneasiness was not thereby allayed for that foundation was so shaken,
that my faith could not stand thereon, and I was still uneasy.
But although it was such a mystery to my natural conceivings, that I could not fathom it;
yet I believed this hope was necessary for a Christian to find, while in health,
the better to support his illness,
and help him to submit himself to the will of God in his death.
My soul was at this time under a weighty pressure;
and although I was then ignorant what it was,
I have since believed it was no less than the drawings of the Father`'s love;
yet as the natural man discerns not the things that be of God,
so he knows not where to seek them.
Thinking I was still lacking that zeal which I saw in others,
I was now increasingly fervent in my prayers; I made additions to my private,
and waited with attention on my public devotions;
and sometimes went on with vigour in the repetition of those exercises.

About the seventeenth year of my age, there came a bishop to the town,
in order for a confirmation, which I thought was a singular good for me;
for from that ceremony I conceived that a steadier
hope and faith in Christ would seize upon my soul;
and I entertained thoughts that there was a peculiar
power given to this high and holy function,
from which I was to reap that which was divine.
I doubt not but the Invisible Being looked with compassion
on the fervent desire of my soul,
and viewed with acceptance the reverential awe in which my mind, as well as my body,
was prostrated to receive the earnest of my wish; and I know that my behaviour,
both before, at, and after that time, was taken notice of by my relations and intimates.

A little while after, my uncle asked what I thought of receiving the sacrament.
I told him I did not believe it was proper for so young persons to adventure; for,
as it is said, "`those who receive it unworthily,
procure to themselves damnation,`" I dared not receive it.
He told me of some that were as young as myself,
and whom he thought as unfit--I told him I knew it,
but they seemed to exalt themselves among their companions on account of that,
which I dared not, in the greatest humility, partake of; neither did I find,
that my faith was sufficiently ripe to comprehend
the mystery between the outward bread and wine,
and the body and blood of Christ.

Here I began to flag in my hopes of having received
any benefit by the laying on of the bishop`'s hand;
and what if I say, I staggered, not only at one thing or two,
but at all that I had done on a religious account.
Did I now believe there was no God?
Oh no! but to my inexpressible grief, I could not find how to worship him,
so as to prove my own acceptance, or the assurance that I longed for;
nor could my soul rest without it.

I had now laboured in my inventions--spent all my hopes; and as a person quite fatigued,
sitting down,
I was made to bear such a mortification as I had never before
known--to see that I was dwindling away from that,
which I thought was most expedient for me to be exercised in,
and that my performances were no more than so many fleeting comforts,
continually wasting in the fruition.

At last I went on so heavily, that I began to be weary of them,
and willing to leave the burden I had contracted in my own will.
I found enough to do to go on with them in their course,
for I found I had gotten them only by tradition.
This was a close time, wherein I was far from exaltation of any kind;
for it was to me hard drawing on without faith,
which I now concluded was the immediate gift of God.
Under this belief I had to cry like the poor publican,
"`Lord have mercy on me;`" and my soul was more justified from these breathings,
than it had ever been in all the wearisome labours I had engaged in.
But the enemy, who is always near to damp the good in us,
troubled me with many of his suggestions,
as that it could never be the way to attain to happiness,
to discharge myself of the worship due to God for his favours;
yet the more I gave way to the thoughts of throwing myself on the mercy of God,
the more also I found a hope to spring within my soul,
that the Lord would point out a way for me.
This drew me still farther from all ceremonies,
and gave my mind such a turn from those diversions I once took delight in,
that my uncle and aunt took notice of it, and called it melancholy.
But it arose from a deep solidity of thought,
not knowing in what manner or path I should be directed--how
I should recover a proper sense of my afflictions,
or obtain a satisfactory assurance.
This pensiveness my uncle and aunt used their endeavours to prevent,
and asked my acquaintance to visit me oftener; but their company so frequent,
suited not my taste: those nights,
that were spent in what I had once thought innocent amusements,
were now made to procure dull mornings; and my desire of being alone,
with the fatigue of so much hurry, put me on thoughts of shunning the occasions.
I therefore desired my uncle to let me go out as a waiting-maid;
but they would not hear of parting with me.

When I was past eighteen, we heard that S. Taylor, a Friend,
was about selling off the goods of her shop, and going to live at Stafford;
and I desired my uncle to buy them for me,
thinking that such an employment might abate the perplexities I was in.
I was then a stranger to her, and my uncle,
who liked this proposal better than the first, being ever ready to please me,
sent for her; and in a little time after, agreed that I should have the goods,
and be with her at times for my better information of the business and customers.
This gave that family and me our first acquaintance,
though I had not the least thought at that time,
that ever I should change my name in respect to religion.
Hence, however, many imagined my persuasion arose,
of which I shall speak in the proper place.
I went at my own convenience, according to our agreement,
still keeping my exercise to myself;
nor did I remark anything particular in my new acquaintance,
their exercises lying hidden as well as my own.

When the time came that I was to enter the shop,
my uncle had so good an opinion of the Quakers,
that he left appraising of the goods entirely to S. Taylor.
I continued to board with my uncle,
and made it a constant rule to go directly home at night when I had shut the shop,
and thus shunned my former associates.
The day I spent in business, and part of the night in much thought;
the desire of my soul increasing after that revival of hope,
which as my little faith in what is called the service of God, still diminished,
I found at times drawing me nearer to a reliance on him,
and a patient waiting for what might follow.

I was now about nineteen, when we received an account of the death of my sister Lydia,
for whom our family went into mourning: and I not only mourned in clothes, but in heart;
for I lived her more dearly than any sister I had, and may truly say,
her death added to the weight of my exercise, as well as to my belief,
that it was requisite for me to know my own election to be sure.
And oh! the distress that I now was in, when I looked upon myself and others,
to see them posting on with cheerfulness in the respective duties of their religion,
and myself not only barren in my desires of it, but so oppressed in the performance,
that I could neither assist my uncle, nor myself that way.
They who have known the activity of nature, can best judge of my state, when my uncle,
who used to show me so much indulgence,
signified his happiness in my good behaviour by saying,
he could scarcely go into company, but they were speaking in my commendation.
It was, indeed, a thing very pleasing to my kind uncle, who told me a little after,
he would have me to be prudent; "`for,`" said he,
"`there are those eyes upon you that you are not aware of:`" and I believe he was then,
in his own thoughts, near having his ambition concerning me gratified, which was,
to see me happily settled in the world, I conclude, that at this time,
the parents of my associates had generally a respect for me; for,
although I was of a brisk and lively disposition, yet was I, through the goodness of God,
preserved from that which was immodest or profane,
and kept within the bounds of what is termed innocent behaviour and good breeding.
This engaged many, that had daughters, to encourage my company.
But how soon did I see a turn! for that which ought
to have raised me higher in their esteem,
now seemed to prove my overthrow therein.
So true it is, that the greater like, once turned, proves the greater dislike.
But to go on--I could no longer remain under the cloud of insensibility;
for the Day-Spring from on high had visited me, and the veil was so far rent,
that I saw the work of God was in the secret of my heart,
and that a spiritual worship must have place there.

I now remembered that I had heard the Quakers recommended
people to mind that of God in themselves,
and to follow the teachings of the Spirit.
This I thought looked somewhat suitable to my condition;
and my mind seemed pressed to look at their doctrine again.
In order to this, as I was not willing to be taken notice of,
I went out between the times of service, as though I would walk.
This was an exercise that was allowed by the most strict,
to take off any drowsiness that might hang on the mind,
and unfit it for the support of the evening devotions.
Though this was not what I had a real necessity for, being one of good spirits,
and before I knew the lack of faith in my way of worship, being in my devotions zealous,
in my diversions lively, and in my work industrious; yet I took this freedom,
because the meeting lay in my way, where I had a mind to inform myself,
and as I passed by the gate, would make a stop.
If I heard no voice, I soon went off; but if anyone was speaking,
I usually stepped within the door, the little end being, as I thought,
a good shelter from the eyes of those who sat in the body of the meeting.
I made these visits as often as I could; and surely I have to say,
the Lord was very condescending,
and gave me a more clear understanding than ever
I had found within myself at the other meetings,
and which, from our house being so near, I had opportunities of.
My intentions were good in respect to these freedoms,
and I used to stay as long as I dared, then take a turn down the next field,
and so to my worship again;
whereby I proved the effect which the different doctrines had on me,
the former answering to the hope of that justification I have before spoken of,
and the latter fruitless and dull.
Yet so far did I proceed in repeating these trials,
that I plainly saw it was with me like those who are hard
to believe the things they would not have to be true;
but so closely did the truth and mercy of God follow me,
that I found judgment in myself from the Almighty,
for persisting in that which gave me not the least satisfaction.
Willingly would I have retained this old profession,
that I had been brought up in from my childhood,
and that was as dear to my natural desires as Ishmael was to Abraham:
but I saw it must not remain, and therefore I made a stop, and refused to go to church,
so called.

I had signified something of my uneasiness to my sister,
who was coming down from London again,
and she had told my aunt that I favoured the Quakers, and did not intend to go to church.
This greatly incensed her, and she left me, saying,
she would fetch out the parson and people to carry me in.
But so far had truth wrought With me, that I found I must not only venture that,
but also struggle against the oppositions which I felt in myself.

The following night was spent in more confusion than common;
and the next day my uncle and aunt went to the parson`'s,
and some time after sent for me.
He looked on me with surprise,
signifying his great mistake in one whom he had thought so religious,
and so good an example to others;
for I was a constant attender upon those called Saint`'s days,
as well as other times set apart for worship.
He asked me how long I had been uneasy--I told him a great while,
and could not find any real satisfaction in anything that I could do.
He signified that a perseverance in those duties I had been instructed in,
was the only way, and would, no doubt, bring that satisfaction I spoke of.

"`But,`" said he, "`your uncle is afraid you are going to be a Quaker.`"
I answered, "`I believe not,
though I have met with that satisfaction from their preaching,
which I never met with elsewhere.`"
He said, it was no more than a delusion of the grand enemy of our souls;
and then set forth how dangerous it was for young persons either to go to hear them,
or to read their books; saying theirs were seducing, erroneous principles,
and he would have me promise, never to hear them any more.

Many heavy things he said of them,
and asked me particularly about the family of the Taylors; these I could justly clear,
and said,
that neither they nor any other person had ever endeavoured to insinuate their principles,
or turn me from one profession to another.
He then said, if I would desist from hearing them, and reading their books,
I might do well, and through the continuance of my duties, and good company,
might overcome my uneasiness.
Indeed, he said so much against the persuasion of the Quakers,
that my respect for the clergy, together with my indifference to the formalities,
as I then termed the customs of the said people,
seemed to determine me never to go to hear them again.
I said, (and that very truly,) I would never be a Quaker, if I could help it:
nor was I one till the desire of my soul for peace could be no other way satisfied;
and no one could wrestle more to escape it than I did,
as the following account will show.

Such now were my childish conceivings,
that though I had witnessed the work of God to be among them, yet I thought,
could I but come to a possession of that which they preached,
and which I found a savour of in my heart,
it would not matter whether I attended any form of worship or not.

My uncle said, the parson, whose name was Leay, would board me,
which he and my aunt thought very well of.
I understood his meaning, and thanked him, but said,
"`that would only give the town reason to believe there had been a difference among us,
and if they would be easy, I would see what I could do in going to church again.`"
But I well remember, what a heavy trial it was; and I went with so much indifference,
that it gave my uncle and aunt great uneasiness, and myself no less.

Not long after, parson Bennet sent for me to the widow Brueton`'s;
he also expressed himself surprised at his being so mistaken in me, saying,
had it happened with many others, he should not have wondered half so much.
We being more equal and intimate, I could be more free with him;
he asked me if I was for being a Quaker--I said, "`I do not know, yet I believe not.`"
"`Why,`" said he, "`they deny the Scriptures!`"
I said, "`If they do, I promise you I will never own them, but I know they do not.`"
"`Why then,`" said he, "`they wrest them to their own destruction,
and they deny baptism.`"
I said, "`They do of water, but they preach a baptism.`"
"`Yes,`" said he, "`and a strange one too; put your finger into that fire,
(one being in the room,) and see how you can bear that baptism.`"
This filled my mind with indignation, and I said, "`No, I scorn it;
for I believe they no more mean elementary fire, than the baptism of elementary water.`"
I may conclude that at this time neither he nor I knew that mysterious baptism,
which my soul has at times since experienced.
He went fluently on respecting the principles of the Quakers,
setting some of them forth as quite ridiculous, and told me, if I could not believe him,
he would lend me some of their own writings.
I thanked him, saying,
I was not in a disposition to read the sentiments
of any one profession;--and indeed I was not,
for even the Scriptures themselves, in which I had been so conversant and taken delight,
seemed to me, just then, of little advantage;
and so great was my separation from all duties, that I found nothing left to trust in,
but God alone.
But to return,--I said, "`I could not judge them by their writings,
but was assured they were so far in the right that, as God was a Spirit,
he must be worshipped in spirit and in truth.`"
He said but little after, only "`If you have got a notion of the Spirit,
you are past hopes.`"

The uneasiness of our family was now no longer a secret: my intimates, one after another,
would accost me by the name of "`flat-cap,`" and "`Friend,`" or deridingly ask,
"`Does the Spirit move thee?`"
with which, and such other mockeries, my natural inclination was much buffeted.
The storm began to be more boisterous, both within and without;
my acquaintance abroad and my relations at home: but above these,
the enemies of my own house, who were always ready, at each difficulty I met with,
to turn the balance against my small hope;
and by insinuating the necessity of my being cautious, and deliberate in my proceedings,
had run me such a length in trying to go on in the way that I was trained in,
that the righteous judgments of the Almighty seized my soul again,
and in so weighty a manner, as made that heart,
which used to spring with joy at the chiming of the bells, now to fear.
That soul, which used to approach the consecrated house with reverence,
now trembled at the entrance; and those steps,
that used to advance towards the pew with pleasure, lost their former activity;
and nothing but horror and darkness ensued,
in the room of the once delightful offerings of prayer and praises unto God.

Oh! surely I have enough to remind myself of here,
without particularizing the afflictions,
which the anxious desire of my kind uncle and aunt for my eternal welfare, produced.
Such I believed it was,
and therefore I endeavoured to bear them with submission and resignation,
as proceeding from a principle of love.
Indeed, I did all in my power to allay their trouble:
the loss of their rest and appetite, and the disquiet of their minds,
being a cause of real grief to me; under which,
the little comfort that I could find within myself was, that I was not accessory to it,
any farther than by studying to find the answer of a good conscience towards God,
and an assurance of that which might go with me beyond the grave:
but this I could not find, in the present distressed situation of my mind.
Notwithstanding, I secretly longed to hear the Quakers once more;
and as my uncle kept a strict eye over me,
that I might have no opportunity of gratifying my desire,
I must account it a peculiar favour, that about this time,
there came a young woman from Newcastle to visit us.
She was a stranger to our uneasiness, and my mind being still pressed to hear as above,
I took her out, as though for a walk, and when we were near the meeting,
asked her if she had a mind to hear the Quakers--she answered me, "`Yes; for,`" said she,
"`there is no meeting of that people at our town.`"
I am sure, had she known the least of our family`'s uneasiness,
she might have read my confusion in my looks when I asked her the question,
and much more when I entered the door,
and heard set forth the disadvantage those lay under, who halted between two opinions.
The minister proved, from the apostle`'s expressions,
"`that a double-minded man is unstable in all his ways;`" and proceeding in that doctrine,
it renewed my hope and faith, that the Lord would still be gracious to me.
I had before known the witness of God that is placed in the heart,
spoken to by several Friends;
yet this unexpected testimony was so adapted to my present circumstance,
and so answerable to the ardent desire of my mind,
of being directed to that path which would lead me to the favour of God, that by this,
and our non-acquaintance, all prejudice was removed,
and a clench given to the nail of my new profession.
For though I did not immediately join the Society,
yet as I could not but assemble with some community,
I found it must be with those whose doctrine now reached my soul;
with a resolution and good intention,
not to persist any longer in a way that I had no faith in;
but to submit myself to the will of the Almighty,
and to follow that which weaned me from a dependence on formal worship.

We returned home; she satisfied with having indulged her curiosity,
and I no less with the hand of Providence in this thing; both filled with admiration,
she at the whimsies of the Quakers, and I at their doctrine;
well resembling the two women at the mill,
the one taken with the truth and the other left.
I could have concealed where we had been, but she could not.
My uncle was informed of it, yet did not take any notice while she stayed;
but when she was gone, he indulged himself in liquor,
as I have reason to believe he did one night before,
in order to give a fuller vent to his passion;
otherwise he would hardly have carried it so far above his reason,
as to use me as he did; for according to his own words,
he had watched occasion to chastise me as a child, yet could find no fault with me,
which could give him sufficient excuse for so doing;
but now he thought nothing was so cruel as to allow me to run on to my ruin,
both of body and soul.

About this time I had put by a young man, who, my uncle thought,
was likely to make me happy: he had proposed to settle on me a sufficient jointure,
and my uncle had offered, out of his own generosity,
to advance a hundred pounds in addition to what I had of my own.
But here how different were our views--my uncle thought of the advancement of my body,
and I was no less anxious for the welfare of my soul;
for I could think of no delight but the immediate favour of God;
and this I felt I must prepare to suffer for,
as I apprehended it stood opposed to their proposals.

My uncle, as I have observed, having drunk much, was violent in his behaviour;
though I could well cover all, as to his intentions, one rash expression excepted,
which escaped him in the conclusion of that night`'s disorder; and which I mention,
to show the reason of my departure from them, and to give an idea how it fared with me.
He said, "`if ever I went to the meeting again, he would bereave me of my life.`"
I stood trembling, yet received the threat in a tender state of mind,
and I could perceive he suffered for it the next moment.
My life was not much in my notice,
neither could I believe my uncle would execute his vow:
but oh! the idea of a separation overwhelmed my mind with sorrow; for I found,
at that moment,
that I dared not flinch from the truth with which my mind had been impressed,
nor could I think of leaving my nearest relations thus.

Many thoughts revolved within me, and many tears flowed,
under the consideration of my unhappy circumstance, as I then termed it.
The enemy of my soul here manifested his malice, by suggesting,
how unlikely I was to obtain any conquest over either myself or my relations;
and that my rash proceedings might bring on a massacre.
But my soul has to commemorate the condescension of Divine Goodness, which,
in this very low state, inspired me with some encouragement; and a desire prevailed,
though I sought it not, to reestablish my little faith,
by again hearing the most penetrating word; and I concluded it would be best,
to moderate my uncle and aunt`'s passion,
by returning directly back from meeting to my own apartment,
which was furnished with a bed and some few necessaries,
bought at my entrance upon the shop:
I had hopes they would look on my so doing with a favourable eye,
and when their hurry was a little over, send for me home.

They did not miss me till I came from that meeting,
and they thought fit to let me stay where I was till the next.
They then sent a person to see if I was there:
but I did not find an engagement in myself to go, either at that time,
or for some weeks after; nor was I so much taken with this newfangle,
as my uncle called it, as to force my inclination in the least degree; for,
could I have indulged myself in the persuasion that one might serve God acceptably,
without going to any public worship, I could, with ease, have remained separate from all.
This deliberation, however, gave encouragement as well as opportunity,
for my old acquaintances to visit me by turns--the younger sort to show their wit,
by railing at what they called the principles of the Quakers--and the more grave,
to set forth, according to their notion, the diabolical tenets of that people.
As one struck dumb, I had but little to say in reply; only at times,
I signified that their doctrine bespoke better things;
but as I had not yet obtained knowledge, by a perusal of their writings,
I dared not attempt, nor did I desire, to be busy in making any defence for them.
My mind, indeed, had not hitherto inclined to consult either men or books,
lest thereby I should be seduced to believe what was not of God; for I plainly saw,
that nothing short of what was so, would satisfy my soul.
I may say, in thankfulness to that Eternal Power which still preserved me,
the arguments used did not abate my travail of soul alter the Divine favour: and,
though I hope I never was one wise in my own conceit,
yet so far did the truth of God in the secret of my soul exalt itself,
that I proved its influences to be mere wise than all my teachers; who, at best,
were but as the hammer to the nail,
in fastening in my soul the impressions which I had received.

In this situation my uncle also visited me,
and the sternness of his countenance was altered.
He kindly signified to me, how hard our separation was to them,
and that if I would but bind myself by a promise, that I would never be a Quaker,
he would give me a deed of gift,
that at his and my aunt`'s decease I should have all they were worth.
I answered him, that if I could make such a promise,
I wanted no farther encouragement than the continuance of their love; but oh!
I could not do it.
We both sat and wept our passion out.
My uncle mentioned my leaving them so abruptly; but instead of inviting me home,
he signified he could now take no pleasure in seeing me, without an alteration.

In a little time I found the balm of Eternal Goodness,
which healed the wound that my mind had been made to endure on truth`'s account.

There now came a young man to visit me that had been a student,
and had received orders with a benefice--not one of the most thoughtful, as will appear.
After he had used the compliment of, Madam, how do you do?
and I had thanked him, he said, "`Why I hear you are turning a Quaker?`"
I answered, "`We sometimes hear that which is not altogether true;
but I suppose what you have to say.`"
"`Why then,`" said he, "`there must be a great change in you;
and a deal of sobbing and sighing, and thouing and theeing.`"
"`And pray,`" said I, "`what have you against that language?`"
"`Why,`" said he, "`it is not within the line of morality, or common civility;
but what is used between men and their beasts,
and more fit to be used to brutes than men.`"
I replied, "`I am very sorry you should think I have already forgotten myself;
but I remember, and know, it is that language which we, in all our prayers,
and in the Litany, put up our petitions in; therefore, take heed what you say, for,
by your saying it is fit to be used only to brutes and beasts,
of what do you make your God?`"
"`O,`" says he, "`I perceive you side with the Quakers,`" "`Yes, so far,`" said I,
"`as to believe that language good enough for man, which is used in honouring God.`"

He went off; nor was it long before my uncle paid me a second visit.
As I now seemed to him at a stand, dubious with whom to join,
he laid before me the profession of the Presbyterians, saying,
he would freely give me leave to join with them.
But from the acquaintance I had with that people, while twice at Manchester,
I knew they dwelt much upon the same things I was in the practice of before;
therefore I was not likely to find with them the satisfaction I was in pursuit of.
My uncle further proposed,
to take the shop and bear the loss he might sustain in selling off the goods,
if I would choose a place agreeable to board at, in any other town;
for he thought the removing me out of the way of shame and disgrace, as he called it,
might be a means of altering my resolution.
But the idea I had conceived of spiritual worship, was so fixed in my mind,
that it seemed to me, that I must have carried it with me,
had I been removed to the uttermost corner of the earth.
I signified this to him; and he, much wondering at my foolishness, left me, saying,
I was certainly bewitched.
Indeed, I myself could, not, at times,
but wonder what it was that bore up my soul against
the many hard things I met with from others,
and the secret temptations that were daily presented to my own mind; which so filled it,
that, in the little sleep I got,
I frequently dreamed of something relative to my exercises.

In one of my dreams, a man appeared, coming up to my door with a sieve in his hand,
and a bag.
He sat down, and opening the bag, put out some wheat into the sieve.
I asked him what he was going to do; he said, "`to separate the chaff from the wheat.`"
Here the enemy shot his poisoned dart against that fear which lodged in me, and,
through his insinuations, made me believe myself the chaff,
blown from my former quietness,
by aspiring after the knowledge of things too high for me.
Oh! the consternation that my soul was in, from these assaults of the enemy,
who now brought up the miscarriages of my life, and my foolish actions,
as so many witnesses against me; while I endeavoured to withstand him by repentance,
and purposes of amendment; pleading with myself the just ground of my present proceeding.
But as I had not the evidence of hope at my own command, I was obliged to suffer,
till I was again revived by the mercies of a God, who would not break the bruised reed,
nor quench the smoking flax.

In this interval, my uncle came again with parson Leay, and still with hopes,
from my staying at home, that they might gain me; but they found their mistake: for,
though I said but little, I was as resolute to prove the truth as ever.
We sat down, and the parson offered to take in writing, any scruples I had to make;
promising either to answer them himself, or to get them answered by the bishop.
I acknowledged his kindness, saying, I did not see how anyone could be serviceable to me,
for it was faith I needed in the whole.
He signified, it was not for the unlearned to pry into the matter of faith,
but to believe according to the canons of the church;
and went on largely in commendation of the wisdom and great
care there had been among the learned fathers,
that there might be no default or error in the articles of our faith;
from there inferring, that it was requisite we should believe them.
I signified that I could not place my trust in man,
but had received a better faith already;
and that I believe I ought to seek God for myself.
He said, "`You are obstinate, and if you do not take care,
you will renounce your vow of baptism.`"
I answered, "`I do not find that troubles me; for I hold it as a matter of indifference,
which will do me neither good nor hurt.`"
He said, "`You are hardened; and if you persist, you will be damned.`"
This struck us silent; and as soon as I could take my looks off him,
I cast them on my dear uncle, whose eyes plainly bespoke his grief.
The parson got up, and said, "`You have need of the prayers of the congregation.`"
I said, "`I know I have need of the prayers of all good people, and desire to have them.`"
As they passed the shop, I heard him say something of my being quite lost,
and my uncle shook his head, and left me in great sorrow.

This was a heavy trial to me, for the enemy aimed his dart again to give a fatal blow,
by insinuating into my mind the doctrine of election and reprobation;
which strengthened those doubtings the late conversation had raised.

What had I here to do?
no person in the world to flee to,
with whom I could entrust my soul! no book to try my cause by! the Bible itself
being still to me as if written in an unknown tongue! no God or Saviour at hand,
nor even any comfortable desire that I was sensible of!
Read, in these expressions, the deep afflictions of my soul,
thus lying under the tramplings of a most desperate fiend!
Could I have found just reason for his upbraiding me with lightness,
it would at this time have certainly appeared;
or could I have believed that God was unjust,
and would inflict eternal punishment on the innocent,
or on a repentant sinner that was willing to turn from every evil way--I say,
could I have reconciled this to his attributes of mercy and goodness,
I must assuredly have fallen by these suggestions of the cruel deceiver,
who now appeared to me in the most surprising manner; producing that exercise, which,
to this present time, gives me astonishment.
For, one night, as I lay in bed, on a sudden, a voice, as I thought,
audible and like my own, cursed the Lord, and defied Heaven; saying, "`Now am I damned,
for I have sinned against the Holy Spirit, and shall never be forgiven.`"
When the words were passed, I felt bewildered, and immediately flung myself upon my face,
crying out, "`O Lord! forgive me; but it is not I, yet, Lord! forgive me.`"
Thus, in confusion, I went on, sometimes begging for forgiveness,
and then denying the fact: and when I did so far recover, as to know how I was, I felt,
from the agony, in a complete perspiration; the bed whereon I lay, for some time after,
shook with my strong trembling;
and it was a considerable time before I could compose myself Yet when I could,
I found that my great God did not accuse me;
but encouraged the sincerity of my desire to look up to him, as God,
who mercifully saves those that trust in his providence;
and is willing to remit the past transgressions of the truly penitent.
And here I proved my hope renewed, and my faith established; yet,
even here I stumbled at the honour I had been taught to give to those divine oracles,
as I esteemed the clergy; and thought I must surely be mistaken,
in supposing there was no more in them than in other men;
nor yet could I lower my high esteem of their learning, and set the illiterate,
(as I had been taught to call them,) on an equal tooting of wisdom,
with those having the high title of reverend.
Yet here did my God help me; for one evening as I sat, low in mind, musing alone,
the everlasting Truth seized upon me,
in an exposition of that remarkable thanksgiving of our Saviour, "`I thank you, O Father,
Lord of heaven and earth, that you have hid these things from the wise and prudent,
and have revealed them unto babes.`"
This immediate favour, from the lovingkindness of the Lord,
had a great influence over me; I arose from my chair,
and fell upon my knees to receive the overshadowings of his power;
and such was the effect, that by its assistance, I cried out from my soul,
a few words in supplication to the Lord, begging a farther manifestation of his will,
and his preservation therein.
This, I apprehend, was the most lively prayer I had ever then made.

When I had waited for a time on my knees, I remembered that I had read the passage,
yet desired to look at it again.
I had no Bible of my own, my aunt having taken mine from me,
telling me I should have no use for it, as indeed I had not much till this time; yet,
being provided with one, I looked for the text, and casting my eye upon it,
found a great alteration in myself, and cause to say,
"`surely the Lamb of God is found worthy to take the book,
and to open the seals thereof.`"
From this time I knew it was not in my power to read the Scriptures in their right signification,
but only as I had the key of interpretation lent me, which I now often received,
to my great profit and consolation.
Thus I became again familiar with my book,
and prized that good companion more justly than I had ever done before;
desiring to be kept in the way I was to go; to have bread to eat, and raiment to put on,
and to be enabled to return to my Father`'s house in peace;
concluding that the Lord should be my God.

While I resigned myself to his holy will, it pleased the Almighty to show me,
that it was not right that I should thus believe, and yet live alone,
without assembling myself with those that I was satisfied
were believers in the same Divine principle:
neither do I now think it would have been good or right; for,
as sure as the Lord thought proper, in his wisdom, to provide helpmates for the body,
so surely does he condescend to qualify many of his faithful servants, to be helpful,
in a spiritual, sense, to each other.
I therefore believed it was right for me to attend meetings,
in order to retain my favour with him.

In this my aunt did not interrupt me till I had been a few times; notwithstanding which,
I had enough to do within myself; the tears I shed at my entrance at the doer,
and on presenting myself before the Invisible Being,
were so many renunciations of my own will.
I used to sit down on the first seat I came to; yet so well did it answer,
that what I sowed in tears at my getting there, I reaped with joy at my coming away.

Going with a soul desirous of improvement, I was often highly favoured,
and had to remember S. Radford`'s recommendation to me,
to "`buy the truth and sell it not;`" as also to be assured of the justice of the Almighty,
and that man`'s destruction is of himself I think it was about,
or a little after this time, that I heard my present uncle, Joshua Toft,^
footnote:[Joshua Toft joined the Society of Friends
by convincement in the early part of his life,
and through obedience to the teaching of Divine grace, became while young,
a good example of religion and virtue.
His concerns in business at that time,
occasioned him to be much from home and in company with such as were unacquainted
with that circumspect demeanour which his religious profession required;
from some of whom, in consequence of his consistent conduct,
he met with ill-treatment.
{footnote-paragraph-split}
But
his mind was so clothed with patience,
meekness, and love, that he was enabled to silence the ignorance of foolish men;
and sometimes their enmity against him for his faithfulness,
gave place to respect and friendship.
He began business in a small way;
but the blessing of Divine Providence crowned his honest endeavours,
and while yet in the full vigour of life, he acquired a moderate competency.
Thus circumstanced,
and with a flow of business which would have enabled him to accumulate much wealth,
with noble fortitude he declined trade,
in order to devote himself more fully to the service of his great Lord and Master.
He came forth as a minister when about thirty-two years of age,
and laboured faithfully in that character for many
years in various parts of England and Ireland.
For about twenty years before his decease he was much disabled from travelling,
by a disorder in his head, which at times affected his understanding,
and which deprived him of sight for more than fourteen of the last
years of his life.
{footnote-paragraph-split}
After this privation,
his mental faculties resumed their former strength, and continued clear till his decease.
He bore great bodily suffering as well as the loss of sight, with exemplary patience,
resignation, and cheerfulness,
expressing his belief that all his affliction was laid upon him in love,
and his hope that he should receive it as so dispensed.
{footnote-paragraph-split}
A short
time before his departure he was much comforted by a secret intimation in these words,
"`I have been with you, I am with you,
and will be with you.`"
{footnote-paragraph-split}
He quietly
departed this life the 15th of the eighth month,
1769, aged upwards of eighty years,
and was interred at Friends`' burial ground at Leek.--(From
the Testimony of Staffordshire Quarterly Meeting.)]
give his testimony to the truth; and I remember it was as one having authority,
pressing Friends to come out of Babylon,
and exhorting them not to partake with her of her sins,
lest they should also be partakers of her plagues;
and though I was very young in the truth,
yet the Lord was pleased so to enlighten my understanding, that I read him spiritually,
and was made a partaker of that life from which the power came.
Nor do I forget the encouragement which I received from another Friend, when,
like a shower of the former and latter rain, he watered the plantation of the Lord,
by setting forth the blessedness with which he will
reward those who forsake all for his name`'s sake, etc.
But, though I could take delight, yet I was not to build a tabernacle here;
my troubles were not quite over; for, though my aunt let me go free a few times,
yet she proposed to perplex me in my new design,
by aggravating the passions she found in herself,
and by giving way to the foolish excitations of others.

The first time she met me in my going to meeting, was with a whip,
and the next with a black hood and green apron.
But I shall endeavour here to be as brief as I can;
for I do not desire to remember the foolish pains she took to mortify me:
yet I feel engaged, gratefully to acknowledge,
that I was preserved above all the ridicule I met with; though,
to many I was a subject of entertainment and diversion.
Some, however, seemed to have compassion for me; though I cannot say that of such,
I knew at that time above three or four.
Among these was one that frequently expressed a concern for my preservation,
and offered to assist me in having my aunt bound over to her good behaviour;
but I felt more desirous to be preserved in a proper decorum towards her.

Others of my well-wishers advised me to leave the town;
offering me a room in their house, and liberty to sell my goods with them.
This, I must ever acknowledge, was a kind part; but, though they pressed my compliance,
I could not find an inclination thereto;
for I conceived that to quit the town would look as though I had done some bad thing;
and I knew no one could justly say any worse thing of me, than that I was a Quaker.
Therefore,
though I could willingly have been out of the noise that my change had occasioned,
yet I rather chose to commit myself to that Hand, which I now believed could preserve me,
and submit to the confusion of this time, till my God should say, it is enough;
not doubting that these things were permitted for the trial of my faith.
Yet, so far did their kindness prevail, that I inclined to ask farther advice upon it;
and, as Samuel Leay had been a few times to ask me how I did, I told him my desire,
and requested him to procure me an opportunity of speaking with one of the Friends Toft.
He He asked me, which?
I said, either of the three brothers, that I could most conveniently go to,
without my uncle or aunt`'s knowing it for I was
much more troubled at their abuse of others,
than of myself.
He told me the next day, that he had spoken to Samuel Toft,
who was willing to give me the hearing that night.

Accordingly I went in the dusk of the evening, Nicodemus like;
not so much for the shame of the thing,
(which I was now used to,) as for fear that my aunt should get knowledge of it.
I did not know, by the name of Samuel, which was to receive me; but,
knocking at the door, he let me in.
Having paid my compliments, I sat down; and introduced our discourse, by saying,
I supposed he was no stranger to the hurry of the town,
and the angry mood of my uncle and aunt concerning me.
I signified that I could not help it, but that, notwithstanding this,
I found myself engaged to join the Society:
I farther told him of the kind offer made me,
but doubting in my mind what would be for the best, I had a desire to ask advice.
He told me, that to go was the most likely way to rid myself of those troubles;
but asked if I had no hopes of my relations being better humoured.
I told him, no; but was rather afraid they would be worse,
for they said they could never rest while I was a Quaker.
He then said, "`It is a nice point to give advice in,
for who can tell what your relations may do in their anger,
or how you yourself can bear it; perhaps the surest way to be quiet from them is,
to accept the proposals of your friends.`"

This, however, was not what I expected, nor indeed, what I desired;
and to bring him more over to my views, I said, "`Do you think.
Sir, there is room to believe I should be presumptuous, if I should stay,
and receive an injury from them?
He said, he thought not, so long as I gave them no just occasion; and added,
"`Young woman, what do you think is best yourself?`"
I answered, "`I would not, willingly, run myself into danger,
neither act any way purposely to provoke them; nor yet do I see how I can, at this time,
fly from their anger, and leave the town, without giving myself secret uneasiness.`"
To this he replied, "`To be sure, we ought to mind that;
for we might go out of one trouble into another, and perhaps a worse.`"
He further asked me, how I thought I could bear the trial; saying,
I had already known something of an exercise of this kind.
I said, "`Yes, I have; and the truth I have found so much on my side,
that I have been hitherto supported through it, and now do not doubt,
but if I should lose my life, in the way of my relations`' anger,
my soul would still be happy,`" He signified, if such was my belief and resolution,
he could say nothing better to me than, Go on and prosper.

Wishing him the compliment of the night, I returned,
desiring to remain stedfast to what I apprehended was my duty; but when at home,
I could not forbear reflecting on the small assurance I had given this Friend;
and especially on the odd appearance, for a Quaker, which I made; for, besides my speech,
I went in full trim.
I had on my hoop, rings on my fingers, and ear-rings in my ears; my clothes, indeed,
were black and white crape mourning, which I wore for my beloved sister,
and therefore my linen was without lace; neither was I thoughtful, at this time,
about my outward dress, my work lay more within.
Nor did my friend regard my appearance so much,
as to overlook the intentions of my heart;
for Samuel Leay told me the next time he saw me, that S. Toft said,
he was satisfied there was that within me,
that would prevail on me to lay my compliments aside;
and it was not long before I found it my place to do so.
I must now mention a probable reason,
why I was not allowed to give my friend a fuller assurance; and which may also show,
how blind I was to my own state,
and how much need I had to crave Divine light to steer my course by; for,
though I seemed to myself to be quite fixed in my purpose, yet I soon found,
by experience, how weak I was.

I received a letter from my dear brother,
(who had kindly paid us a visit on the death of my
sister,) saying that he had heard from my uncle,
the melancholy affair that was among us;
describing the fanatical and fantastical deportment of those I was about to join with;
the utter mistake they lay under, in respect to the doctrines of Christ,
and giving me a kind invitation to come to him,
with a promise to take care of me and my fortune.
He affectionately mentioned an opportunity he had
of placing me with a near relation of his wife`'s,
who was a milliner in the city, if I liked that business;
and concluded in much brotherly love, and with desires for my welfare every way.

This so sensibly touched the natural affection I had for him, that,
had I not been favoured from the Most High,
with a sight of the snare which my enemy had laid for me,
I should certainly have accepted this offer from my only brother;
the consideration of whose love, in this instance,
and of the grief I had given my other near and dear relations,
caused me to turn my exercises round and round again; and to consider the cause of them.
In this affecting survey, many were my secret supplications to the Lord,
for his preservation and assistance,
that thereby the enemy might be defeated in all his stratagems.
Thus was I attacked on my weakest side; for this tender treatment from my brother,
and my uncle`'s three last visits,
gave me more affectionate concern than all their abuses.
But now I was to answer the letter, and I did it so thoroughly, according to that wisdom,
which my Heavenly Father was pleased to favour me with,
that I never heard any more from my brother on that subject;
but whenever afterwards he wrote to me, it was in great love and respect.

Through the condescensions of the inexpressible love of my God,
I had surmounted many difficulties and doubtings in my own mind;
yet had I various trials still to wade through, as now will appear.

The alteration of my speech was in this manner:--one morning, as I lay in bed,
a weighty exercise came closely over my mind; and as I waited to know the cause,
it came before my view, that I must use the plain language.

I had, before, had this at times under my notice,
and now had hardly time to reconsider the thing and prove it was the truth,
before my aunt knocked.
I knew her step, which made me tremble, and therefore I made no great haste to dress;
but as I knew I must submit, I went towards the door, saying, Who is there?
What do thou want?
She said, Let me in and I will tell thee.
I did not in the least question that; and she quickly let me know it,
by many threatenings of what she would do, if ever I thou`'d her again.
I could not but think it was a very hard allotment to me,
that I must begin this required alteration with my aunt; yet,
from the satisfaction which I felt in my own mind, I was encouraged in the truth,
and from that time I did not shrink from that part of my testimony, except to my aunt,
whom I in no way delighted to vex, and therefore, as much as possible,
I evaded the singular language; and yet, rather than use the plural,
would many times break the thread of our discourse; till I plainly saw it would not do,
and that I must either break my peace, or commit myself to my aunt`'s fury.
This I soon experienced; for using the word thee to her, it so inflamed her, that,
as there stood a fire-shovel in her way, she took it up and struck at me.
My sister being in the little room, caught hold of it,
or she would probably have done as she had threatened,
for the room or closet behind the shop was so narrow, that I had no room to draw back.
Thus was I once more preserved;
but had reason to fear I should yet be the cause of bringing my aunt to much disgrace,
as she often declared, that she believed it was no more sin to kill me, than a dog.

I found she had heard of my being advised to leave the town; and I believe,
I suffered much for that kindness of my friends.
My aunt`'s hopes seemed now, that either they would draw me,
or she should drive me out of the town, for she said that, if I would be a Quaker,
I should not be one in her sight.
And now I had the former kind offer renewed--P. Heller
sending me an invitation to come to Whitehaugh,
for a quarter of a year, till my aunt should be better reconciled.
This was indeed a kind invitation from one that I had never spoken to;
and I might have gone, for any business or school that I then had;
for my aunt`'s behaviour had so frightened the scholars,
that their parents thought fit to keep them at home;
and had it not been for the sake of seeing one called a Quaker,
I should hardly have sold so many trifles as I did;
but there seemed a general curiosity to see me.

Standing, thus, as an object of disdain and derision,
I could willingly have accepted the kind invitation of my friends; yet,
when I cast my eye toward the Captain of my salvation, I found I had not liberty to move;
and therefore, with an acknowledgment of their kindness, I passed it by.

Another proof of my aunt`'s unguarded passion soon after occurred,
which was this:--we were sitting together in the little room, as we very often did,
and it was drawing towards the middle of the night; when,
in the course of our conversation,
she obliged me to use that language which she could not bear,
and a brass candlestick standing between us, she flung it at me with such force,
that it struck against the wall: I had just time to see her intention,
and by stooping escaped the blow.
Thus did David`'s God again preserve me, for the sake of the stem of Jesse,
that now began to bud within my heart: and although I stood here in jeopardy of body,
yet I was mercifully preserved in stability of soul,
and in a supporting belief of being in the way of my duty;
and was favoured with hope as an anchor in this assurance,
that if it pleased the Lord to permit the death of the mortal part,
he would be pleased to let his mercy light on my immortal soul,
and I should die as a martyr to my faith in Christ.
Yet, a fear for my aunt prevailed over me;
and though I had concealed her behaviour towards me as much as possible,
yet this I dared not conceal, lest I should be chargeable with the consequence.
I therefore desired my sister to tell my uncle of this violent action, and my fears.
He returned for answer, that whatever treatment I met with, was good enough for me;
and as to my aunt, it was impossible to keep her at home.

The grief that I passed under, for fear of my aunt`'s going quite distracted, was great,
and the bowings-down of soul and body were frequent,
with earnest supplication to the Almighty for the
preservation of us both--she in her senses,
and me in the way of my duty towards him,
and in a justifiable behaviour to my uncle and aunt.
I believe my uncle had, at that time,
more compassion for me than he would allow to be seen: he had my aunt talked to,
and would not allow her to come at such unseasonable hours again;
for she had several times before spent most of the night with me alone;
and what I then received from her, the Almighty knows, and indeed,
did make up to me in her reconciliation afterwards.
Her nightly visits here ended; but they had been so long continued, late and early,
that I had habituated myself to spend the nights in the little closet,
where I used to keep a fire.
I sat much there, and when it was bed-time, if my aunt was absent,
would put out my candle and sit as still as I could lest
I should be suspected of keeping disorderly hours.

I had here no intimate to converse with, or encourage me,
and was left as a person quite alone; but the immediate visitations of divine favour,
at times, did most graciously establish my faith; and when almost overwhelmed,
the Lord would, in the condescendings of his compassion,
direct my mind to some passage in the Scriptures for my consolation; and I seldom read,
or contemplated on them without tears.

Yet how quickly did I lose the sight and effect of these favours; while,
like a traveller, driven away from the haven of his happiness by contrary winds,
I was forced by grief into a confusion of thoughts,
having frequently sat under the violent suggestions of the enemy till two, three, four,
or five o`'clock in the morning; and was sometimes no sooner in bed,
than my aunt would call me up.
It is hardly credible how little sleep I went with: but surely,
I sympathized with my uncle and aunt in the affliction I gave them.
Food was to me as trifling as sleep,
whereby I proved on what a little nature will subsist: my meals were no ways constant;
a bit of bread and cheese with a little water or milk,
or bread and butler with a dish of tea, were my only food for months;
nor did I desire anything else, till necessity obliged me to alter my course.

My aunt, though under some restraint, used to tell me, she would make me suffer yet;
saying, no one had any business with what she did to me.
One market-day, she fallowed me as I went behind the counter,
and kept me there for some hours; saying, she would hear my language today;
and though I desired her to let me go, yet she would not;
nor did I choose to put her away.
I was, indeed, under exercise,
and desirous to do my duty in the sight of the Divine Being,
though apprehensive I must suffer for it.
When any came into the shop, she told them I was the new-made Quaker;
and filled those who were strangers to her, with admiration of us both! and I may say,
I blushed as much for her as for myself Each time she thus exposed me,
she held me by the left arm, which was next her; and when I used the plain language,
she pinched me very badly; and so often renewed her pinches,
that it was very hard for me to bear them.
Yet I saw no way to avoid her ill usage, without using her as I never had done,
and bringing guilt on myself; I therefore endeavoured to hold out a little longer;
and have since wondered how I bore it without complaining.
She had, indeed, inured me to suffer; and, would often say, the Quakers had taught me;
and if she smote me on one cheek, I must turn the other.
She tried me so much on this occasion, that I many times desired her to forbear;
yet had no hopes that she would regard my petition:
but as my arm and hand were very visibly swelled, I wished them to plead for me;
and by often looking at them, brought them under her notice; when she tauntingly said,
"`I doubt I have hurt your arm;`" and in a little time went away.
When she was gone, I tried to unbutton my sleeve, but my arm being so very much swollen,
I could not.

Doctor Gravesnor`'s daughter, knowing my aunt had been with me a long time,
and seeing her go out, stepped in, and helped me to unbutton my sleeve;
and seeing the condition I was in, went for her father.
When my wristband was loose, my hand and arm swelled to such a degree, that,
before the doctor came, I could scarcely shut my fingers.
When he saw my arm, he said it was a very bad bruise; it seemed,
for the space of the palm of the hand, to be like a jelly,
and exceedingly black toward the shoulder.
The doctor seemed surprised, and said, he was afraid it would mortify; then went home,
and quickly returned with a medicine.
He was one who had always shown me great respect; and his daughters were my scholars,
till my aunt thought proper to break up the school.
I believe it was both from his respect and fear, that he took the freedom,
after I he had dressed my arm, to scold and blame me for my foolish,
childish assent to her treating me so; saying, my case was dangerous,
and I might lose my arm, if not my life; yet he added,
that he would do all in his power to prevent it.
I told him I was satisfied with his kindness and judgment; and I was more willing,
that time, to give up my life than my arm:
yet I struggled in the secret of my mind to submit to the will of God; and the doctor,
seeing my tears fall, said, "`No, indeed, you have enough to bear,
without being chided`" and so I found; for, besides my inward exercise,
his application was very sharp.
He often said he was afraid of the bone; and that it was such a piece of cruelty,
as none in their senses could be guilty of.
He stayed with me a good while, repeating the dressings often, which renewed the pain.

My fingers were swollen stiff, and useless, for I could neither close nor move them.
The doctor asked me, who I had to be with me, since I left my uncle`'s; adding,
that now I could not do without assistance; and charging his daughter not to leave me,
till I had got somebody.
When he left me, he directly sent for my uncle,
and told him in how unchristian-like a manner my aunt had used me; adding,
she was more fit to be bound than to go loose;
and that he ought not to allow her to come to me.
My uncle promised she should not: yet this did not move his pity,
to induce him to come and see me, which was what I greatly desired.

It was a month before I could turn my arm behind me, to dress myself.
My sister had been sent to school at Manchester, for fear, as I have thought,
of her catching the infection of a Quaker;
nor did I much repine at the loss of her company,
for I found that she had acted treacherously between us.
But few in this illness came to see me; yet I heard that many were displeased at my aunt.
Among those few that came, my present aunt, S. Whitehead, was one;
and her visit was very acceptable, though I had then no acquaintance with her.
She spoke to my encouragement, and invited me, when I was better, to come to see her;
which I could willingly have done, but thought proper to delay it some time,
for fear my aunt should know it,
who spared no one that she heard spoke to me in a friendly way.

S+++.+++ Taylor, at this time, lived with John Winter, at Stafford;
and seeing my uncle and aunt`'s groundless dislike to that family,
I had desired they would not visit me often.
They saw my motive, excused the freedom I took with them, and when I went to them,
behaved to me in a loving and free manner.

Here I ought not, and I hope never shall, forget the best of visitors,
the Invisible Comforter; who, in a good degree, made my afflictions easy,
and consoled my spirit, under a belief that I was persevering in the way of my duty.

From the encouragement that I thus felt within, I was excited, as soon as proper,
to endeavour to go to meeting again: and when I had so far recovered as to dress myself,
I thought, from my weakly state, it would be better for me to board in a family,
that I might be in the way of getting such provision as my constitution required;
which had never been very strong, and was now much impaired by excess of trouble,
and my different course of living.
As there was a door from my apartment into the other part of the house,
I thought it convenient to board with Thomas Turnock, who lived there;
and I was well satisfied to do so.

I had now some hope, from my aunt`'s absence during the last month,
that she would no more interrupt me in going to meeting: but soon found it frustrated,
whether by accident or information, I know not.
For, one day, when I came to the corner, near my uncle`'s house,
I saw her coming towards me.
The thoughts of the doctor and my arm quickly occurred; and I concluded,
should I allow it to be hurt again, the consequences would be very bad.
As I was at liberty, it seemed right to keep so, and make the best of my way;
yet so embarrassed was I, that, before I had gone many yards, I faltered in my purpose,
and my aunt got up with me, before I was halfway to the meeting.
I now saw my mistake,
and that it would have been better if my aunt had overtaken me sooner;
for the place looked dangerous, and the lack of room to shake and push me about,
gave me many apprehensions that she would throw me headlong down the precipice.
It was about the time that Friends were going into the meeting,
and this vexed her the more;
for I have reason to believe she could not endure the sight of a Friend, on my account.
She did not spare to tell me of hurting my arm, nor to shake me by it;
but as it had some folds of flannels around, it was preserved.
My endeavour to out-walk her was not suddenly forgotten; she,
many times after made mention of it,
and would signify that God was above the wicked spirit still.

Thus, with many admonitions and exhortations, as she called them,
she kept me till the time when she might expect the meeting to break up,
and then left me.

Being at liberty, I went towards the meeting, and as it was not over, I stepped within,
that my aunt might know that my intention was resolute.
This seemed to be a renewal of our acquaintance, for she soon repeated her visits,
though not at the former unseasonable hours.

I have, many times, seriously reflected how it was with me in these straits,
and may acknowledge that my composure was owing to a divine power,
which stayed my mind on God, and kept down those passions of nature,
which otherwise might have exceeded their bounds.
But, Oh! the calmness and tranquillity that did in these times of trial possess my heart,
while innocency prevailed over shame:
and I found by submission to these lessons of mortification,
that I grew in patience and resignation--in the desire after the Lord`'s favour,
and the manifestation of his will,
for he brought my heart into so good a degree of submission,
that I was willing to undergo, or be termed anything,
rather than lose the enjoyment of that in which I had now a small possession.

It was about this time that I knew an ecstasy of joy,
at the freely giving up my name to that, which I once thought the most despicable.
There came a London haberdasher to my shop, with whom I dealt in business:
he approached me in his customary manner; and as I did not answer his compliment,
as usual, he looked full at me, and said, "`Are you a Quaker?`"
My soul was struck with this home question; I solemnly answered,
"`Yes;`" and immediately a spring of joy seized my heart, accompanied with this desire,
Not only a Quaker, Lord; but grant me to be an Israelite indeed.

From this time my good desires were strengthened, and the ambition of being an Israelite,
became my exercise.
But here I cannot but remark, how like a fool I appeared in my own eyes;
for there seemed as great an alteration in me as could possibly happen from such a change.
I could not now be fluent in compliments,
and saw it best to keep out of extravagance of words,
and such a latitude in discourse as I formerly indulged in.
So many cross words and knotty queries lay in the way of all I seemed to have to do,
that nature was abashed, almost beyond the hope of recovery;
yet I often contemplated the benefit that accrued to Zaccheus from that heavenly call,
"`Make haste,
and come down:`" and how willingly would I have made my situation similar to his;
believing there was something in that call alluding to the glories of eternity;
which now appeared of brighter lustre to my eye,
than all the glittering objects of a transitory life.
Surely the time would glide sweetly on,
in reciting those refreshing prospects which attended my intervals of grief;
but the sequel of my history calls on me to cross my inclination.

It was about this time that John Toft gave me an expectation of a visit;
but that evening I was threatened with a disappointment; for,
my aunt came in high displeasure, and by her upbraidings raised a crowd about the door,
which occasioned him to pass by.
When she had wrought herself into a disposition to be more quiet,
she shut the door and sat down.
I turned out of my mind the thoughts of her unkind behaviour,
yet could not help feeling regret at the loss of the Friend`'s company,
being desirous to see him, as he had been instrumental for my good.
While I was musing on these things, a messenger came and told me,
that although my aunt was there, if I thought it convenient, he would come to see me.
I hesitated a little, to prove what would be best; knowing my aunt`'s weakness,
that she would not spare me, nor mind, in her passion, what she expressed; yet hoping,
as it was his desire to come, that he would excuse what might fall upon himself,
and see through the falsities she might cast on me.

With this conclusion I requested his company; and my aunt being present,
said she would stay to see this Friend.
On his knocking, I let him in, with a degree of fear,
and watched to hear the salutation she gave him which was:--"`You
deceiver! you antichrist! you have seduced this silly wretch.`"
Had she known what my heart could have told her, she might have thought differently;
for on the appearance of the Friend,
I was made very sensible of that power by which I had been drawn into the truth.

He endeavoured to show her the unreasonableness of her charge, by assuring her,
he had never had any conversation with me, nor had visited me before.
She answered, "`If you have not,
your brethren have;`" and proceeded with violence against the Quakers.
He still tried to engage her attention, by reminding her that his mother and she used,
as neighbours, to be acquainted: she signified that was true,
and if ever there was a good Quaker in the world, his mother was one.

She walked to and fro between the shop and the closet,
laying many heavy things to my charge, which I had learned with silence to bear,
till she touched my modesty,
and told the Friend the freedom which she said I gave to young men;
when I desired her to keep to the truth.
She said, "`If I spoke another word she would knock my head against the wall;`" which,
I well knew, a word or two more would have aggravated her to do.
Upon his asking, "`How long I had been so bad,`" she said,
"`ever since I had been deluded; for I was well enough before I was bewitched.`"

Thus she went on, as long, I believe, as she had power; for, going out, she said,
"`I will go, but I will come again.`"
But she came no more till next day, when she laid on me with blows,
saying that I sent for the Friend on purpose to vex her.
She had showed so much of her passion, as to make the Friend remark to me,
that he could think no other than that she was out of her senses;
and that he could not see, if I had not truth for my foundation,
how it was possible for me to stand.
I told him that I had no other view of coming among Friends,
than to procure the truth and peace of God unto my soul;
and that I had still hopes I should be preserved.
He observed to me the emptiness of a barren profession;
and advised me to wait on God in the secret of my heart, to rely on his wisdom,
and to trust in his power, expressing a desire that I might be preserved; and adding,
he would have come to see me sooner,
but found himself engaged to take the apostle`'s advice,
to "`lay hands suddenly on no one;`" and after kindly inviting me to his house,
took leave.
This visit I returned in about a month.

When he was gone, I considered what had passed,
and was thankful to the Great Disposer of all things.
I thought there was somewhat extraordinary in my aunt`'s leaving us,
for she had never left me with any person before,
and I was glad I had an opportunity of gaining such instruction,
as I had never before received in conversation;
nor could I less admire the Friend`'s prudent care, in observing the apostle`'s advice,
which I had before thought alluded only to the laying on of the bishop`'s hands,
at the time of the young student`'s admission into holy orders,
and the confirmation of youth.
But now I knew, by experience, that, for lack of prudence in particulars,
I had been a sufferer: and as an instance,
shall mention one of the most uneasy meetings I ever attended;
which was occasioned by a Friend`'s over-care,
who had often pressed me to come up higher than where I frequently sat.
I remarked,
that the highest place in the meeting would be as
little regarded by my aunt as the lowest,
should she be inclined to make a disturbance there; yet, on frequent importunity,
being willing to show some respect to the Friend`'s advice,
I was prevailed with to advance a form or two.
But when she came and saw I had not thoroughly taken her advice, she took me by the arm;
and though I signified my desire of sitting still, as far as civility would bear,
yet she compelled me to rise,
and notwithstanding I showed a desire of turning
in at the first and the second seat I came to,
yet she would not let me rest, till she had placed me by herself.

Then, Oh! the hurries that my mind was in; for surely, had my aunt herself been there,
she could not have confused my thoughts half so much: for though, at this time,
when at meetings, I had a desire to draw nigh with Friends in spirit,
yet it went much against my inclination to sit so near the place which,
my aunt used to tell me, must be my seat; saying, all proselytes must be made preachers,
and tell to the brethren the abominations of the wicked.
Often would she tease me with such things; well knowing,
I had in my nature a great aversion to women`'s preaching.

Here I sat, in a restless condition, several times purposing to go out;
yet the regard I had for the Friend prevailed on me to stay.
Glad, however, was I when the meeting broke up;
and when it was over she gave me her hand; which I answered with my own,
in token of forgiving her too forward, though loving act; yet not without telling her,
when at home, the trouble she had given me, and desiring her never to use me so again.

Shall I here say, that good came out of evil?
no surely, but sweet came out of bitter;
for by this Friend`'s freedom of giving me her hand,
several that were in the meeting did the same;
and though this did not prove a time of confirmation to my faith, but rather otherwise;
yet it seemed like a sign of union, no one having done so before, and was pleasant.

I lost, for a time,
the deep impression which the Friend`'s apprehension of my aunt`'s being distracted,
had made on my mind; but thought afterwards, if, from the little he saw,
he entertained apprehensions of that kind, what had I to fear,
who had seen her so many times, a great deal worse; yet, what could I do,
or what was there to be done;
I could not renounce my salvation in order to appease my aunt.

These reflections caused distress in my countenance, which occasioned my aunt to say,
that she read the very Quaker in my face.

It seemed hardly possible I could ever know any sorrow like what I then felt;
and my aunt, either by information, or her own observation, became acquainted with it;
and by many frantic gestures, wrought in me a belief, that she was really as I imagined.
My soul now fled to the Almighty for refuge,
and I sat before her a witness of her frantic behaviour,
with more solidity and composure than she expected.
At last, she came up to me, and said "`I am mad; you,
you have driven me mad! and I am mad!`"
I was surprised to hear her say so, and thought there was some hope for me,
as she had yet so much reason left as to tell me
of the thing she knew I was so afraid of.

Upon my showing so much indifference about it, she abandoned that scheme, and soon after,
as one fainting in her hopes of victory, desisted from interrupting me in the street;
yet, wishing to obstruct my desire of going to meeting,
she would come to my room before the hour appointed; telling me,
we would have a silent meeting, and I would gladly have had her keep to it,
but it seemed an impossibility on her part.

When I saw it was her intention, by this practice, to keep me at home,
in order to prevent it, I set out so much the sooner; and she, on the other hand,
came still earlier, till she saw, that unless she rose sooner in the morning,
my resolutions would outgo hers.

Many were the paces which I was forced to take in the fields on this account;
but my labour was not in vain, for my aunt then left me to my liberty,
and many precious meetings I enjoyed.
As I had nothing of tradition to trust to, when there,
my earnest desire was to seek the Lord; and he was found of my soul,
to my inexpressible consolation.

In, respect to silent meetings,
my spiritual exercises at home had taught me how to improve by them:
my heart inclining rather to sit in fear and reverence,
and to watch against the tumult of unnecessary thoughts, than to be busy, as formerly,
in the florid appearances of lip-worship.
But yet, I would not have it supposed, that I knew no difficulty in my exercises;
for surely,
I have often felt the throng of natural cogitations to press so closely upon me,
that I have found cause to implore the divine aid, and to breathe forth this cry: Lord,
if you keep not the city, the watchman wakes, but in vain!

But though I was freed from my aunt`'s molestations,
I found it was only as the changing of a scene,
and that the subtlety of the serpent was now more dangerous to me,
than the rage of the lion had been.

My freedom of attending meetings, from which I had hitherto been much restrained,
and the Lord`'s mercy in subduing those spirits which
were a hinderance to my soul`'s serenity,
I could not but gratefully acknowledge, with desires that I might answer the obligation.
But I was yet inexperienced in the craft of the enemy and deceiver of men,
and needed the assistance of some prudent intimate friend,
whose counsel might have set right bounds to my zeal.
This subtle one, taking advantage of my earnestness,
cunningly twined a thread of his own into that work which
I was endeavouring to render acceptable to my God.
I had, till this time,
been taken up in seeking after an increase and establishment
in the knowledge of the truth,
and in keeping up a strict circumspection in my behaviour,
that thereby I might not give my relations and acquaintances just occasion of trouble,
or a pretence for vilifying the way of truth.

I had not yet made any great observations on dress, but thought to make a stand,
and judge what was best to be done; and doubtless, so far I was in the right,
while I made some alterations.

But now I found the prowling adversary, what he ever was--a malicious, deceitful,
twining serpent, who,
if he can but get in his head at the least opening of our inadvertency,
will soon introduce his body, under an appearance of sanctity, to effect, if possible,
the utter destruction of the soul.
He saw that his aim of drawing me into any gross, obvious evil, was defeated:
and as I had seen less of his stratagems in the angelical form,
he now insinuated himself into my desires of being zealous for the honour of God,
and elevated me above my proper height; so that I fell to judging, cutting,
and trimming of!`" every superfluous scrap from my dress; and not content with this,
I went from my apparel to my shop.
In less than a week, I made several sacrifices of value;
and so hurried was I in this blind zeal, that I seemed impatient for more fuel.
And having gone through, as I thought, at home; I next let out the busy eye on others.
There were but few who escaped my judgment, forgetting that tender advice,
(Luke 6:37) "`Judge not, and you shall not be judged; condemn not,
and you shall not be condemned.`"
I noticed each point of behaviour and apparel; till so great a critic had I become,
that I seemed all speculation on the more minute things;
neglecting the weightier matters, as faith, mercy, and the love of God, which, surely,
I ought to have regarded, though not to have left the other wholly undone.

To what extravagance I had gone in this respect, the all-penetrating Eye best saw,
and was pleased to look in compassion on the mistake of my intentions,
and most graciously to illumine my understanding; giving me plainly to see,
that I was quite out of that charity, without which, the apostle says,
all our works profit nothing.
So tenaciously did I adhere to this thing, that I saw not the deceiver,
till I discovered such passions predominant in me, as I had never observed before.
My temper became uncharitable, and unmerciful; I looked with an evil eye on the innocent:
and was incapable of either pleasing myself or being pleased with others.
But according to the greatness of my error herein, so was my abasement;
and I was at length brought down so low,
as to be capable of hearing the small voice of Wisdom, saying,
"`Who has required this at your hand?`"

Now was I filled with shame; the serpent had beguiled me,
and by his cunning had given me more uneasiness than by all his roaring.
I acknowledged my fault, and begged forgiveness and future protection of the Almighty;
who in his great condescension, made up the breach and restored the path to walk in.
Yet had I given the vaunting one room to sport with my indiscretion!
and he would often bring into my thoughts the loss I had sustained,
by his poisonous insinuations,
even when no more of the effect of it remained than was
necessary to guard me against the same devices in future.

This exercise was scarcely abated, before another trial occurred.
My relations being still displeased that I should stay in the town,
thought of another stratagem, which greatly surprised me,
and added to the trouble which the destruction of my substance, as before related,
had given me.

My uncle having been to London about our affairs, reported on his return, that,
on account of a large debt of my father`'s, who had been dead thirteen years,
a suit in Chancery was commenced against him.
This report ran current; and my uncle gave out, that as I was under age,
he would take again those effects which he had put into my hands,
though I had not received one quarter of my equivalent.

The unwelcome intelligence was brought to me by many.
I say unwelcome, because I had contracted some debts in the way of business, which,
my uncle said, he could and would refuse to pay.
My aunt had broken up my school,
and my former acquaintance having withdrawn their custom, my, trade was at a stand,
and had been so above a year, except for some few trifles, as before mentioned;
so that I was now sensible, that the things I had destroyed were not my own.
Having some acquaintance with Counsellor Hollingshead, I laid before him my straits,
and he civilly told me, I might be quite easy on account of the debt; adding that,
if there had been any truth in it, he should have heard of it from my uncle,
who used to take his advice; and besides,
he knew my father`'s creditors had met with due honour.
In respect to my uncle`'s taking back the effects he had entrusted me with,
it was at his pleasure, and he might refuse to pay the debts contracted,
if the bills were made in my name, unless he had given his promise to pay them.
The Counsellor desired me, if I had any farther trouble, to let him know it,
and he would speak to my uncle for me.

Thus was I fully satisfied concerning my father`'s debt; and in a little time after,
was comfortably visited with the breathings-in of the love of God,
in these few comprehensive words: "`Fear not, I have overcome the world.`"
Had my trouble been even redoubled, like Job`'s,
surely I should in this season of favour have forgotten it.
Yet when it subsided, I found there remained two occasions for sorrowful reflection:
the one was--paying off my creditors; which I soon got over,
as I had cash enough to balance all but one, from whom I had received a parcel, which,
through the smallness of business, was nearly entire, and this I sent back,
with money to answer any deficiency or damage.
It was kindly received, and I was very easy respecting it.
But as to the other affair--by destroying the articles,
I had put it out of my power to restore them; and this dwelt longer with me; yet,
as I lived to come of age, I took the debt myself, and became reconciled to bear it;
though not without a belief, that if I had had a friend to give me advice,
it would have been otherwise.

Here I bemoaned myself before the Almighty, that I had lost my parents,
disobliged my relations,
and had no friend to take more notice of me than
is common among the generality of professors;
and, indeed, how could I expect that any would busy themselves to take the care of me,
in any degree, without my express desire?

I became more and more sensible of the danger to which my years,
as well as other circumstances, might expose me;
and I preferred many strong desires to the Most High, that,
in his wisdom he would appoint for me a faithful friend, who would check my errors,
as well as encourage me in virtue; one that was capable of instructing me by experience.
These desires were often accompanied with a promissory hope and belief,
that I could subject myself to the counsel, and bear the reproof of such a one;
but where to find such a friend I knew not; I was afraid to trust my own judgment,
and often supplicated the Invisible Being to direct me in the choice.

Accordingly, it thus happened: J. Toft was visited with sickness, and brought so low,
that several Friends who met, did not know but it must be to take their final adieu.
I had also the favour to be in the chamber, and heard many things worthy of regard;
but that which struck me most deeply was,
his expression of an earnest desire for my preservation in the truth,
and a kind recommendation of me, as a young person, to the Friends present,
that they would have me under their notice.
I was truly touched with this sense of paternal care, and secretly desired his life,
and the restoration of his health; which, as it pleased the Almighty to grant,
I was no longer at a loss for a friend; conceiving that in him,
whose kindness towards me was manifested under such circumstances,
I might reasonably hope to find such a one as I desired.
From that time I looked on him with a just regard, and with a resolution that,
whenever I found occasion for advice, I would apply to him for it.
Nor was it long before my exigency seemed to require it.

The Beloved of my soul, who, in my tender state, had so graciously replenished my heart,
now hid his face from me; and I was not indulged with those times of solace,
which I before had so plenteously enjoyed:
I waited and waited the return of the dearest object of my soul, often querying.
Why stays my Beloved so long?
or, What have I done since his last visitations,
to occasion his thus hiding himself from me?
Impatient, I sought him in my chamber, in meetings,
and in the fields--places where I had used to receive his favour;
but these seemed now to have lost their lustre,
as well as my Beloved his benevolence towards me.
I sought him, but I found him not: like the spouse, in the Canticles, I was ready to ask,
Have you seen my beloved?
I was disconsolate days and nights, and I may say, I mourned as one needing her mate.
Still I thought my tears moved not his pity, and his ear seemed deaf to all my cries;
while the imperious watchmen wounded me,
and the cruel enemy upbraided me with all I had gone through for my Beloved`'s sake,
telling me I had better have stayed in Egypt, than thus to languish in the wilderness.
Great were the conflicts I here met with, not knowing why it should be thus:
and fearing I was dying to all that was spiritual,
I at length resolved to make application to my friend.

I went to his house; and while I waited a suitable opportunity to speak to him,
the tears trickled down my cheeks: yet when I had unbosomed my complaint,
I received great satisfaction; for, from his kind inquiry of my past conduct,
I found my opinion of his friendship confirmed.
From his tender advice my soul was encouraged to hope a little longer: and,
to my inexpressible joy, in some days after,
I felt the influence of Divine Love suggesting to my mind, Follow on to know the Lord;
Joseph, the spiritual Joseph, is yet alive.
Oh! surely here I found again that inestimable jewel, the pearl of my best affection,
and the life of my hope, with such revivings as Jacob experienced,
when he saw the assurance of the welfare of his son:
and my soul bowed under a humble sense of gratitude; saying.
It is enough, I will go down and see him before I die.

It was a time of true humility, tenderness, and love.
My covenant was renewed; and it remained for some time as a summer season, or,
"`as the time when the voice of the turtledove is heard.`"
Yet at intervals, I could not but reflect on former days, and conclude,
that the smallest degree of my uncle and aunt`'s reconciliation,
would add to my happiness.
As these thoughts increased, so did my desire of making a trial;
and one evening I went to their house, and knocked at the door, stranger-like,
as indeed I was, not having been there for above two years.

Their maid let me in; and I suppose I much surprised them.
They were sitting alone by the fire.
I just said, "`How do you do?`"
and stood within the house, a little distant from the door.
My uncle looked very sorrowful, and if he spoke at that time, he only said,
"`I have no pleasure in seeing you.`"
My aunt said enough, and called me many impudencies for coming.
I stood about half an hour, and then bidding them farewell,
my aunt came with me a part of the way back, scolding me as we went,
I thought this was but poor encouragement, yet was truly glad I had seen them.

In about six weeks I had a desire to go again.
I went in the former manner, knocked, and stood as before;
and after a little while my uncle said, "`You may sit down.`"
My aunt then fetched some books, (which, I believe,
were the same that Bennet would have lent me), and read several absurd passages;
to which I only said,
"`I hope you do not think that any sect can be so
ridiculous as to believe and practise those things.`"
During this interview my uncle sat at a distance; I stayed a little longer than before,
and my aunt let me come home quietly.

Thus I went several times to see them, watching for permission;
believing that to go without it, might expose me to danger:
but in my fourth or fifth visit, my uncle said to the maid, "`Set her something to eat.`"
I could truly have said that his love was sufficient;
for I was so satisfied with this little return of it,
and with my aunt`'s increased quietness, that my heart was ready to overflow.
I went to the table, and before I ate, a contrite thanksgiving arose in my soul to God.

After this, I took the liberty to go at sundry times to see them,
and had frequent opportunities to remark, that I still had a place in their affection;
which answered my desire; nor could I hope for more, as there always was, and is,
a contrariety between the spiritual and natural dispositions.
They continued to return my visits, and behaved kindly to me ever after.

A little past the twenty-fourth year of my age, I was married,
with the approbation of my friends, to Samuel Lucas:
he was a worthy man and well respected.
My uncle would not come to the meeting, but came to our dinner;
and my aunt visited us the next day.
They both behaved lovingly and affectionately to my kind husband; and afterwards,
were very tender of our children, my aunt exceedingly so; and indeed,
it yields me satisfaction, as often as I remember the public testimonies she gave,
before her death, of my behaviour towards her in the time of my convincement.
Though I believe she continued to think it was right in her to
restrain me from going on in a way so different from her own judgment,
and from what she thought was right; yet she acknowledged that she was angry,
and exceeded proper bounds; and that she never saw me behave unbecomingly,
or heard me give her an unhandsome word.
She was, again, as civil to Friends as before I went to meetings;
and at times asked several Friends of my acquaintance to her house,
and entertained them freely.

I may now conclude my narrative thus far, with truly saying,
how blessed I was in my situation! having a loving, kind, and tender husband;
our lawful endeavours made prosperous; the affections of my relations restored; and,
above all, the blessing of the.
Almighty sanctifying these enjoyments to my soul, to the praise and adoration of his love.
Here was I permitted to dwell as under the pavilion of the goodness of God,
yet not without something still to combat with in my secret exercises.

I thus persevered comfortably for two years after my marriage, when the best Physician,
whose penetrating eye saw the malady of my soul,
prepared a bitter cup for the purging out a venom that lurked there,
which I had imbibed from the malicious adversary of truth, before, and even after,
my going to meetings, and which remained to this time.
Hence issued a fiery trial,
by which my professions of faith and affection were to be proved.

This may well be as a second part of my history, and was the most trying,
as it went very near to my spiritual as well as temporal life.
The war was not with flesh and blood, but with the Majesty on high;
under the prince of the power of the air, who rules in the children of disobedience.

I have before observed, that to be an Israelite indeed, had attracted my desires;
but little did I suspect what I had to undergo, before my heart was cleansed from guile,
and delivered from that wrath which the enemy had
been heaping up in me against the day of wrath.

To introduce this heavy relation, I must go back to my childhood,
and say,--that the first time I ever heard a woman preach,
from a prejudice imbibed from my companions, and probably an aversion in my own nature,
I thought it very ridiculous; and the oftener I had opportunities to witness it,
the more I secretly despised it.
At the time that I joined with Friends, this was one of my strongest objections to them;
but I endeavoured to silence it, by concluding that others might do as they pleased,
and so would I.

My aunt, as I have hinted, often alluded to it, as she knew my dislike to the practice,
from my former confession; and I have no doubt, the serpent, by means of this prejudice,
injected his venom the more deeply; for since I have found out his workings,
I have remembered a secret fear, which I had at times on this account,
and which this cunning enemy had allayed,
by reminding me of my many protestations against it.
The apprehension, however, continued, that I should certainly become a preacher,
which greatly distressed me:
the allowance of women`'s preaching being the only dislike
I had to the discipline and order of the church;
yet still I satisfied myself with many inconsiderate resolves against it.

A good opportunity was allotted me for shaking off
those shackles which the fiend was fastening on me;
but which I lost, and have remembered it many times with sorrow.
Being in discourse with a Friend, he frankly asked me, if I had any scruples?
or whether I was satisfied with the principles of Friends?
I stopped short in my mind, apprehending, if I should mention women`'s preaching,
that he would think I spoke with regard to myself.
Thus was I baffled; and I answered,
that I was satisfied in the principle itself At that time my idea of preaching was,
that it was an act of love and friendship, separate from obedience;
and glad could I have been, like Moses, if all the Lord`'s people had been so inclined;
women excepted.

I continued thus for some years, until I became such a slave to my fears,
that I could not say, "`Your will, O Lord, be done;`" but, like Naaman,
the captain of Syria, would eagerly be excused from this thing.
I now began to believe that such exposures were something more than voluntary offerings,
and was convinced, from many proofs,
that my state had been as clearly spoken to by my own sex, as by the other; yet,
such was my perverseness, that, one day, I had much difficulty to stay the meeting,
+++[+++when a woman Friend ministered,]
though I could not help acknowledging within myself,
that it would have been an acceptable testimony, had it come from a man.
Thus great was my prejudice; but greater, yes I may say, infinitely greater,
were the condescensions of God;
for I was still favoured in my waitings with a sense of his living presence.
The mysteries of true divinity were opened to my understanding;
and through the influences of divine love has my
cup overflowed with such acknowledgments as these--"`Oh,
my Beloved! if you deal so bountifully with me,
my breast will be too narrow to contain your love; Oh! withhold your hand,
or I shall certainly speak of your goodness to others.`"
And I really believe, had I embraced that opportunity,
and joined with the Lord in his workings on my mind,
I should have been delivered from my fears and escaped those
cross occurrences which I have since waded through:
but here my poor soul shrunk from the cross of Christ, whose yoke, to the passive mind,
becomes easy and his burden light.
Such was my weakness,
that through short-sightedness and the false suggestions of the enemy, I started aside;
and may truly say, the longer I carried my burden, the heavier it proved: and I now have,
with regret, to look back and confess,
that instead of closing with the visitations of love, I joined with my inveterate enemy,
and resolved not to wait for or encourage any farther discoveries.
Thus did I harden myself, wretched creature that I was!
And when I have felt the power of the Almighty moving with love upon my mind,
I have no less than said,
"`I will have no more understanding;`" and have sundry
times shut my eyes when the book has been,
as it were, put into my hand, and the best Interpreter has been near.
So I withstood that tender love which followed me;
and have risen from my chair to fix my thoughts on other objects.

My soul is deeply affected with the goodness of God
in the continuation of his mercies towards me,
and under a sense of the sad state I was then in, while the enemy had rule,
and He who shed for me his most precious blood,
was rejected at the hazard of the salvation of my soul;
so I sat down far short of a true Israelite.

Thus went I on, stifling conviction, till I was lulled into a spiritual lethargy;
in which I lay, till the compassionate God, who wills not the death of a sinner,
was pleased to arouse me to a consideration of what I had been doing:
and I found enough to do to keep from sinking under the bitter
reflections I had brought upon myself by my rebellious proceedings:
yet through the unutterable goodness of God, I was again revived by his favours.

Having recovered a little from this state of deep affliction,
I was visited with weakness of body;
so that both myself and others thought I was near death: but it pleased the Lord,
in an unexpected hour, to give me this assurance--"`You shall not die, but live,
to declare what I have done for you,`" This was still so contrary to my desires,
that I could not rejoice at the lengthening of my days;
for now I believed I should certainly be tried.
Oh! the days and nights of conflict that followed this intimation.

My countenance changed, my health seemed daily impaired;
the solitary places were made witnesses of my grief;
and as the years increased so did my exercise, till I had another visitation of sickness,
and was, to all appearance, past recovery.
Most willingly would I have yielded unto death;
choosing rather to die than live to be any more disobedient:
and it pleased the Lord to prove me again and again in the secret of my soul,
whether I would live to be obedient to his requirings, or die: my choice was,
rather to die than live to be a preacher.
Yet it pleased him in his wisdom to raise me again,
contrary to the expectation of those that beheld me; none of whom, at this time,
knew anything of the exercise of my mind,
which increased to such a degree as cannot well be expressed.
My body trembled as a thing shaken; and my groans were like those of a dying person.
But I had learned, by dear experience, to cleave unto the Lord;
and when I felt the power, what if I say, of his might,
I sought out places most proper to receive it, and bowed in prostration:
from the weight of it I have affectionately burst forth in this language, "`Lord,
what would you have me to do?`"
And as I believed it was a preparation for a further exercise,
I often begged that he would be pleased to make me
able to bear whatever he should think fitting,
in his wisdom, to lay upon me: indeed, sweet was his love, and merciful his dealings,
many times renewing his covenant with my soul.
Yet here I was not to continue, but was led again to the test of my fidelity.

Being in meeting, in a comfortable frame of spirit,
I found a motion in my soul to worship God in vocal prayer;
and although I had known the same power in my own chamber,
and with pleasure submitted to it there, yet here, not yielding to the impulse,
my heart and all that was within me became confused; the whole fabric was shaken:
and this was taken notice of by a Friend that sat behind me, who,
as soon as meeting was over, asked me how I did; saying, she was sure I had been ill.
I answered, (as well I might,) that I was but indifferent.
This seemed a good caution to me, as I desired to keep my exercise to myself.

Not many more meetings passed before I was tried again;
when I fixed my body as firmly as I could, but found it impossible to still my mind,
knowing too well how it was with me;
though the whisperer would persuade me it was all imagination.

In this way I trifled so long,
that the displeasure of the Almighty seemed hot against me,
and life and death were set before me.
I was in confusion, both at home and abroad, wishing myself any other creature.
I harassed myself, till I could bear it no longer;
and at length concluded it would be best to mention it to a Friend: I did so,
and he signified that it had been for some time on his thoughts
that something of that sort lay upon me.
And though I here proved, that it was not in man,
by the force of argument and tender advice, to subject my stubborn will,
yet I received some advantage, and acknowledged the truth of his remarks: I did not,
however, closely follow them, but became in myself as a piece of contradiction.
Sometimes I would follow the Lord, and then resolve otherwise:
I went to meetings as a slave goes to his labour.
At home I dared not sit down in solitude, being sure to meet with judgment;
and into company I could not go,
without wounding myself by pretending to be what I was not;
I was unwilling to be suspected of being grave,
and concluded that every one who looked on me earnestly, knew how it was with me.

Thus was I harassed, as between the upper and the nether millstone;
often wishing for death, and that I never had been born.
Great was my strait; I could not go back again,
because I was not able to shake off the principle of truth;
but had thoughts of flinging myself into the jaws of death.
Yet, forever praised be the name of the Lord,
his mercy withheld the devourer and preserved me;
giving me to see into his false insinuations, and to believe that the life,
which it was in his power to take at his pleasure,
would not be a sufficient atonement for those rebellions I had been guilty of;
and I was brought to an abhorrence of the thoughts which I had conceived.
Herein did the goodness of the Lord appear so evidently,
that I resolved to keep close to meetings.
But alas! when there, instead of keeping close to my exercise,
through fear I kept myself from it, and sat, as it appeared to me, empty, void,
and waste:--empty of those desires I used to possess--void
of all that was good--and waste,
as being laid aside by the Almighty;
and all through a slavish fear that I could not draw nigh to God.
I sat as though I had nothing to do but to see, with a wishful eye,
others partake of that food which my soul stood in need of.
Yet my state was different from that of being at ease in Zion;
for when I looked at those who, I thought were in a right frame of mind,
they seemed to me to be feeding at the Lord`'s table,
while my hungry soul stood in a state of estrangement from him,
without courage enough to seek the scattered crumbs.

Thus it was with me many days; till in one meeting, growing faint,
a state of drowsiness overtook me, a thing with which I was not naturally beset;
yet so far did it prevail, that I was forced to pinch myself, to keep awake.
Now I thought myself worse than ever I had been in my life;
for in childhood I had the form, which I left to possess the power.
Here I found not so easy an access as I had expected; and though I sought and sought,
instead of meeting with my True Friend, I met with my enemy,
dressed in the doctrine of election and reprobation.
Into this I had been led some years before, and now I had much difficulty,
through the sense of my own unworthiness, to shake it off;
labouring hard against the temptation of destroying myself,
and foolishly wishing that some accident would do that office.
But here the riches of God`'s grace again appeared: I was brought to see and acknowledge,
that if my soul perished eternally, the Lord was but just in his dealings with me;
and these considerations had some effect.
I desired to be brought back to my former state, that I might have access to his power,
be a witness of his love, and be tried once more.
My pen would fail,
fully to set forth the condescensions and long-sufferings
of the goodness of my Creator towards me.
I here knew my pardon sealed: but my peace lasted not long;
for I was quickly tried again and again; and still I did not give up.
I was sensible that I flinched from that Power which was ready as a hand to help me,
and therefore became worse and worse.
"`It will never be better with you,`" suggested the enemy.
I knew not which way to turn: I was weary of my own obstinacy,
and would now see what I could gain by self-mortification; and as I could not work,
I would eat but little.
I studied several ways to afflict myself; and thought,
glad should I be if I had no tongue.
Here again I knew the old prompter to be near to augment my distress; which,
with my own disobedience, made the whole creation appear to be against me.
Oh!
I was in such perplexity, that I said, "`Now shall I fall by the hand of my enemy.`"
I fretted and chafed at myself and everything about me,
and could not attain true submission.

At one time, as I was seriously reflecting on my situation,
these thoughts passed my mind and surprised me; "`If you are a God of power,
make me willing.`"
This was no sooner past, but they were followed by the suggestion, "`Soul,
detest this presumption; for though he is a God of power,
it is in his own time that he will redeem.`"
I was astonished, and said, "`Lord, what is it?`"
and it came thus before me; "`There is war in heaven,
Michael and the dragon.`"--When the flutter was over,
I remembered the passage where it is said,
"`In the day of my power my people shall be a willing
people;`" and I was comforted by it.

There also fell out another singular occurrence about this time, which I cannot well omit.
I was fully persuaded that if I went on in this obstinacy, my house would be laid waste;
and within a month afterwards, we had, in the view of many spectators,
a wonderful deliverance from fire; during which,
while others were busy in considering how it should have happened,
I was busy in reflecting on myself as the cause;
which weighed me down in humble acknowledgments unto God, for his merciful preservation.
The world, comparatively speaking, seemed now to be near at an end with me;
and it was as if a total eclipse was drawing on; every scene and object looked gloomy;
and whichever way I turned my eye, an angry God appeared.
There was no shelter for me--nothing now to defend myself
with--no way of escaping--and nature must yield.

In a little time the trial of my obedience came again;
and at that moment the enemy of my soul suggested,
that if I got up I should not be able to stand; but thanks to the Almighty,
I was strengthened to try, and found him a liar.
The expression of a few words produced a blessed change.
There seemed now a new heaven and a new earth; old things passed away,
and all things belonging to my state, became new;
no more sense of guilt for past disobedience remained;
but new embraces and new covenants filled up that joyful day.
Yet I looked forward with anxiety to another meeting day;
and though I formerly thought meetings did not come fast enough,
yet now they seemed to come too soon.
In two or three of them, I sat under a degree of slavish fear;
yet truly desired to keep my integrity and obedience.
At length a second trial came; I was moved to kneel down; and while I viewed the place,
my soul secretly breathed thus before the Lord,
"`Here is the place of my execution;`" and seeing the boss,
"`This is the block whereon I must yield up the pride of nature,
for a testimony of my obedience; remember me,
O Lord! and the conflicts that I undergo to serve you.
Accept, O Lord! the sacrifice.`"
I then kneeled down; and when I arose,
this came into my mind--"`the life that I must now live,
must be by faith in Jesus Christ.`"

Persevering in obedience, it wrought unspeakable satisfaction, and brought my soul,
by degrees, out of the place of thraldom and bondage.
Thus, by the goodness of God, were the strong holds of sin and Satan brought down,
and the joy of my salvation was restored.
Meeting-times and days were pleasant again, while my soul worshipped the living God,
as in the house of prayer.

While I stand as on the bank of deliverance, resounding hosanna in the highest,
having the harp of thanksgiving put into my hands,
my song shall be of mercies and of judgments,
through which my soul has been so far redeemed; and of the victory of the Lamb,
by whose right hand and everlasting arm, my soul`'s enemies have been driven back,
scattered, and put to flight.

Now, what have I to render to my God for this most glorious work,
the salvation of my soul,
but the humble acknowledgment of one of the most unworthy and vile of sinners; who,
by his most gracious condescendings,
is enabled and encouraged to ascribe unto him honour, adoration, dominion and renown,
with praises and thanksgiving, as due to his eternal love, forevermore.

Upon perusal of the same,

My soul`'s enliven`'d with a`' flame

Of holy zeal, that I may know

The hand of God in all I do.

Oh, that I may therein confide,

And by the righteous Judge be tried!

This is of my desire the scope,

That of my love, my faith, and hope,

I may not be asham`'d; but have

A heritance beyond the grave:

Which to enjoy, Lord, grant that I

In fear may live, and favour die;

And that my soul may on the wing

Of hallelujah meet our King.
