[#testimony.style-blurb, short="Testimony of Staffordshire Quarterly Meeting"]
== The Testimony of the Friends of the Quarterly meeting of Staffordshire held by adjournment at Leek, the 3rd of the Fifth month, 1770.

Margaret Lucas, of Leek, was educated in the national worship;
and being religiously inclined in her youth,
she strictly conformed to the external rites and ceremonies thereof;
but finding them unavailing to obtain that peace of soul she sought after,
was engaged to frequent our meetings;
in which she persevered amidst the opposition and cruel treatment of her relations.

For several years she appeared at times +++[+++as a minister,]
in a few words, to the satisfaction of Friends.
While of ability, she was a diligent attender of our meetings;
and sometimes under much weakness and infirmity of body;
she was also exemplary in observing the time appointed.
With becoming composure and resignation of mind,
she submitted to the severity of a long and painful disorder;
and calmly departed this life the 24th,
and was interred in Friends`' burying-ground at Leek, the 26th of the sixth month, 1769,
aged near 68 years.
